### ISSUE TITLE
just wanna know  can this lib be used to cooperate with grpc?

### ISSUE THREAD

**Issue by ihjmh** [bdarnell/tornado_http2#4]
since the grpc is use the http2, on the client side ,i wanna use tornado to accept requests and execute the func in grpc server side? is this possible? or is this a good idea ? thanks a lot

**Comment by bdarnell** [comment]
Not at this time. GRPC relies on some relatively obscure HTTP features including Trailers, which are not yet implemented in this library.

**Comment by ihjmh** [comment]
@bdarnell thanks a lot,but i use this to make grpc work in tornado
```
def _fwrap(f, gf):
    try:
        f.set_result(gf.result())
    except Exception as e:
        f.set_exception(e)

def fwrap(gf, ioloop=None):
    """
        Wraps a GRPC result in a future that can be yielded by tornado
        Usage:
            @coroutine
            def my_fn(param):
                result = yield fwrap(stub.function_name.future(param, timeout))
    """
    f = gen.Future()
    if ioloop is None:
        ioloop = IOLoop.current()
    gf.add_done_callback(lambda _: ioloop.add_callback(_fwrap, f, gf))
    return f
```

it seems work well....did i miss something important? can i use this in real program?

**Comment by bdarnell** [comment]
I've never used grpc from python before (only from go), so I can't answer your questions about grpc usage. This looks like it will probably work, although it may not be the simplest solution (depending on what exactly the grpc `future()` method returns).

**Comment by ihjmh** [comment]
@bdarnell  thank u very much
